apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-flask-app
  name: my-flask-app
  namespace: gcp-devops-project-prod
spec:
  ports:
  - name: flask-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: gcpdevops
  type: LoadBalancer
status:
  loadBalancer: {}