steps:
- name : "gcr.io/cloud-builders/docker"
  args: ["build","-t","gcr.io/$PROJECT_ID/gcpdevops","."]
# images:
#    - "gcr.io/$PROJECT_ID/gcpdevops"
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kuberenetes-manifests/*
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1-c	
  - --cluster=gcp-project	
  - --namespace=gcp-devops-project-prod