steps:
- name : "gcr.io/cloud-builders/docker"
  args: ["build","-t","gcr.io/$PROJECT_ID/gcpdevops:$BRANCH_NAME","."]
# images:
#    - "gcr.io/$PROJECT_ID/gcpdevops:$BRANCH_NAME"
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops:$BRANCH_NAME']
  # create the namespace 
  #step 4
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: bash 
  args: ['-c','gcloud container clusters get-credentials --project=$PROJECT_ID --zone=us-central1-c gcp-project && kubectl create namespace gcp-devops-project-$BRANCH_NAME || exit 0']
  # env:
  # # - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  # # - 'CLOUDSDK_CONTAINER_CLUSTER=gcp-project'
  # # - 'CLOUDSDK_CORE_PROJECT=gcp-project-400416'
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kuberenetes-manifests
  - --image=gcr.io/$PROJECT_ID/gcpdevops:$BRANCH_NAME
  - --location=us-central1-c	
  - --cluster=gcp-project	
  - --namespace=gcp-devops-project-$BRANCH_NAME
options:
  automapSubstitutions: true
  #- --deploy-parameters="$BRANCH_NAME=$BRANCH_NAME"